version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: pas12345
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mini-ecommerce-rabbitmq-network

networks:
  mini-ecommerce-rabbitmq-network:
