version: '3.6'
services:

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    #restart: on-failure:10
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8201'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-config:/vault-config
      - mini-e-commerce-vault-volume:/data
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: /bin/sh /vault-config/workflow-vault.sh
    networks:
      - mini-e-commerce-vault

volumes:
  mini-e-commerce-vault-volume:

networks:
  mini-e-commerce-vault:
