version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mini-ecommerce-db-network

  broker:
    image: confluentinc/cp-server:7.4.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9991:9991
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://broker:29092,INTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: "false"
    networks:
      - mini-ecommerce-db-network

  connect:
    image: debezium/connect:2.4.0.Final
    hostname: connect
    container_name: connect
    depends_on:
      - broker
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: broker:29092
      REST_ADVERTISED_HOST_NAME: connect
      REST_PORT: 8083
      GROUP_ID: compose-connect-group
      CONFIG_STORAGE_TOPIC: docker-connect-configs
      OFFSET_STORAGE_TOPIC: docker-connect-offsets
      STATUS_STORAGE_TOPIC: docker-connect-status
      KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: All
    networks:
      - mini-ecommerce-db-network
      
  user_svc:
    image: debezium/postgres:16-alpine
    ports:
      - 5433:5432
    healthcheck:
      test: "pg_isready -U user_svc_user -d user_svc_db"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      POSTGRES_DB: user_svc_db
      POSTGRES_USER: user_svc_user
      POSTGRES_PASSWORD: user_svc
    volumes:
      - user_svc_db_data:/var/lib/postgresql/data
    networks:
      - mini-ecommerce-db-network
  
  auth_svc:
    image: debezium/postgres:16-alpine
    ports:
      - 5434:5432
    healthcheck:
      test: "pg_isready -U auth_svc_user -d auth_svc_db"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      POSTGRES_DB: auth_svc_db
      POSTGRES_USER: auth_svc_user
      POSTGRES_PASSWORD: auth_svc
    volumes:
      - auth_svc_db_data:/var/lib/postgresql/data
    networks:
      - mini-ecommerce-db-network
      
  product_svc:
    image: debezium/postgres:16-alpine
    ports:
      - 5435:5432
    healthcheck:
      test: "pg_isready -U product_svc_user -d product_svc_db"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      POSTGRES_DB: product_svc_db
      POSTGRES_USER: product_svc_user
      POSTGRES_PASSWORD: product_svc
    volumes:
      - product_svc_db_data:/var/lib/postgresql/data
    networks:
      - mini-ecommerce-db-network
  
  order_svc:
    image: debezium/postgres:16-alpine
    ports:
      - 5436:5432
    healthcheck:
      test: "pg_isready -U order_svc_user -d order_svc_db"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      POSTGRES_DB: order_svc_db
      POSTGRES_USER: order_svc_user
      POSTGRES_PASSWORD: order_svc
    volumes:
      - order_svc_db_data:/var/lib/postgresql/data
    networks:
      - mini-ecommerce-db-network
  
  payment_svc:
    image: debezium/postgres:16-alpine
    ports:
      - 5437:5432
    healthcheck:
      test: "pg_isready -U payment_svc_user -d payment_svc_db"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      POSTGRES_DB: payment_svc_db
      POSTGRES_USER: payment_svc_user
      POSTGRES_PASSWORD: payment_svc
    volumes:
      - payment_svc_db_data:/var/lib/postgresql/data
    networks:
      - mini-ecommerce-db-network

volumes:
  user_svc_db_data:
  auth_svc_db_data:
  product_svc_db_data:
  order_svc_db_data:
  payment_svc_db_data:

networks:
  mini-ecommerce-db-network: